### ISSUE TITLE
Want to learn: "@sveltejs/kit": "npm:@tal500/kit@1.8.3-legacy-builds-12", where did this package pull from? Do you have an article?

### ISSUE THREAD

**Issue by xuxchao** [Tal500/sveltekit-legacy-demo#3]
Thanks thank you

**Comment by Tal500** [comment]
I used Google translate and the result is "thanks thanks".

You're welcome!

**Comment by xuxchao** [comment]
Want to learn: "@sveltejs/kit": "npm:@tal500/kit@1.8.3-legacy-builds-12", where did this package pull from? Do you have an article?

**Comment by xuxchao** [comment]
The main content is the title, not just the content. Hey hey

**Comment by Tal500** [comment]
Ah OK, please write this in English so I can understand better.

You asked where the package is from, so the short answer is:
https://www.npmjs.com/package/@tal500/kit

This is a fork of SvelteKit 'kit' package I'm maintaining of PR sveltejs/kit#6265(and all the info appears there), until hopefully legacy support will be merged.
You can see in this page that the "homepage" field refer to the branch 'legacy-builds-versioning', which is a fork of the branch 'legacy-builds' for "temporary" clean fork NPM version purpose.

Hope it answers, you're welcome also to maintain your own fork of PR sveltejs/kit#6265 if you wish to use it carefully since it's unofficial.

Additionally, I'll edit and translate your messages for now.

**Comment by xuxchao** [comment]
Oh, oh, OK. Thank you for your answer. It turned out that it could not be sent to the npm warehouse. I am just wondering why we need to specify an npm:?

**Comment by xuxchao** [comment]
Oh, oh, OK. Thank you for your answer. Originally, it was also published to the npm repository. I am just wondering why we need to specify an npm:?

**Comment by Tal500** [comment]
> Oh, oh, OK. Thank you for your answer. Originally, it was also published to the npm repository. I am just wondering why we need to specify an npm:?

This line of code:
https://github.com/Tal500/sveltekit-legacy-demo/blob/565de0610f9e051e3ce175fdd4fe9c6b471863c4/package.json#L18

tells to NPM: "Install the package @tal500/kit@1.8.3-legacy-builds-12, but name it as a package named "@sveltejs/kit"".

This makes all the `import ... from "@sveltejs/kit/*"` to work, even thought the NPM package name is now forked to be "@tal500/kit".
An example of such import, in:
https://github.com/Tal500/sveltekit-legacy-demo/blob/565de0610f9e051e3ce175fdd4fe9c6b471863c4/vite.config.js#L3

**Comment by xuxchao** [comment]
Oh, I see. Thanks for clarification
